/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.distribuidos.cliente.gui;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.distribuidos.cliente.controlador.Controlador;
import co.edu.eam.ingesoft.distribuidos.compartitrpantalla.dto.ListaUsuariosDTO;
import co.edu.eam.ingesoft.distribuidos.compartitrpantalla.dto.SolicitarConexionDTO;
import co.edu.eam.ingesoft.distribuidos.compartitrpantalla.dto.SolicitarVideoDTO;
import co.edu.eam.ingesoft.distribuidos.compartitrpantalla.modelo.Usuario;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author caferrer
 */
public class Ventana extends javax.swing.JFrame implements Observer {

	private Controlador control;
    /**
     * Creates new form Ventana
     */
    public Ventana(Controlador control) {
        initComponents();
        this.control=control;
        listaUsuarios.setListData(control.getUsuarios().toArray());
        control.addObserver(this);
        setTitle(control.getUsuario().getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taREcibidos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taEnviar = new javax.swing.JTextArea();
        btnCompartirPantalla = new javax.swing.JButton();
        btnEnviartxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios conectados"));
        jScrollPane1.setViewportView(listaUsuarios);
                
        
        taREcibidos.setColumns(20);
        taREcibidos.setRows(5);
        jScrollPane2.setViewportView(taREcibidos);

        taEnviar.setColumns(20);
        taEnviar.setRows(5);
        jScrollPane3.setViewportView(taEnviar);

        btnCompartirPantalla.setText("compartir pantalla");
        btnCompartirPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompartirPantallaActionPerformed(evt);
            }
        });

        btnEnviartxt.setText("Enviar a todos");
        btnEnviartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviartxtActionPerformed(evt);
            }
        });
        
        JButton btnVideo = new JButton("Video");
        btnVideo.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		Usuario usu = (Usuario) listaUsuarios.getSelectedValue(); 
            	
            	//Setear los datos en el dto
        		SolicitarVideoDTO dto = new SolicitarVideoDTO(null,usu,null);
        		
        		//Mandamos el objeto al metodo controlador
            	control.solicitarVideo(dto);
        		
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnCompartirPantalla, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 462, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(btnEnviartxt))
        						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(btnVideo))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 499, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnCompartirPantalla))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 410, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnEnviartxt))))
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(btnVideo)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviartxtActionPerformed

    private void btnCompartirPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompartirPantallaActionPerformed
        //Se obtiene el valor del usuario a pedir peticion
    	Usuario usu = (Usuario) listaUsuarios.getSelectedValue(); 
    	
    	//Setear los datos en el dto
		SolicitarConexionDTO dto = new SolicitarConexionDTO(null,usu,null);
		
		//Mandamos el objeto al metodo controlador
    	control.solicitarCompartir(dto);
    	
    }//GEN-LAST:event_btnCompartirPantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompartirPantalla;
    private javax.swing.JButton btnEnviartxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Object> listaUsuarios;
    private javax.swing.JTextArea taEnviar;
    private javax.swing.JTextArea taREcibidos;
    // End of variables declaration//GEN-END:variables
	@Override
	public void update(Observable o, Object arg) {
		
		if (arg instanceof ListaUsuariosDTO) {
			ListaUsuariosDTO dto = (ListaUsuariosDTO) arg;
			 listaUsuarios.setListData(dto.getUsuarios().toArray());
			 
		}		
	}
}
